// <auto-generated />
namespace Medi_Care.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SignIn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SignIn));
        
        string IMigrationMetadata.Id
        {
            get { return "201903271458286_SignIn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
