// <auto-generated />
namespace Medi_Care.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPatientIdInReception : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPatientIdInReception));
        
        string IMigrationMetadata.Id
        {
            get { return "201904250548186_AddPatientIdInReception"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
